# Generated by Django 4.2.14 on 2024-08-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='state',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
