# Generated by Django 4.2.14 on 2024-07-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carzone', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teams',
            new_name='Team',
        ),
    ]
