# Generated by Django 4.2.14 on 2024-07-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_description_alter_car_doors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_photo_3',
        ),
        migrations.RemoveField(
            model_name='car',
            name='car_photo_4',
        ),
    ]
